apiVersion: wso2.com/v1alpha1
kind: Component
metadata:
  name: adptx-backend
  labels:
    app: adptx-backend
    component: backend
spec:
  type: service
  runtime:
    type: python
    version: "3.9"
  ports:
    - port: 8000
      protocol: TCP
  env:
    - name: PORT
      value: "8000"
    - name: HOST
      value: "0.0.0.0"
    - name: DEBUG
      value: "false"
    - name: GROQ_API_KEY
      valueFrom:
        secretKeyRef:
          name: adptx-secrets
          key: GROQ_API_KEY
    - name: INDIAN_KANOON_API_KEY
      valueFrom:
        secretKeyRef:
          name: adptx-secrets
          key: INDIAN_KANOON_API_KEY
  resources:
    limits:
      memory: "1Gi"
      cpu: "1000m"
    requests:
      memory: "512Mi"
      cpu: "500m"
  healthCheck:
    path: /api/health
    port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
